### ISSUE TITLE
Have you tested your code?

### ISSUE THREAD

**Issue by Qbuer** [afedulov/google-web-search#2]
真是令人失望
Such Disappoint

**Comment by afedulov** [comment]
This repository was not used by me for 2 years and it was not updated for the last 10 months. Google might have changed something in their API. If you experience a specific problem feel free to describe it in a constructive manner or contribute to a fix.

**Comment by Qbuer** [comment]
Thanks for reply and apologize for my bad manner.
But the problem is i even can't build this project, and there are some
obvious mistake,i think one should be responsible for his craft.
Anyway thanks for you work.

2017-04-11 15:51 GMT+08:00 Alexander Fedulov <notifications@github.com>:

**Comment by afedulov** [comment]
Cloned the project, opened in IntelliJ with Java 1.8 as a Maven project. Everything still works. I think the problem is in your setup. As for obvious mistakes - share them, let's discuss. Alternatively contribute a fix.
